### ISSUE TITLE
New lists aren't recognized by postfix

### ISSUE THREAD

**Issue by g4rf** [g4rf/dockerized-mailcow-mailman#1]
When you create a new list and try to send an e-mail, *postfix* responses with `User doesn't exist`, because *postfix* won't deliver it to *Mailman* yet. The configuration at `/opt/mailman/core/var/data/postfix_lmtp` ist updated but not overtaken from *postfix*. The **workaround** is to restart *postifx* manually:

```
cd /opt/mailcow-dockerized
docker-compose restart postfix-mailcow
```

**Comment by danil-smirnov** [comment]
Hey, interesting work :)
Are you sure the configuration hasn't seen by Postfix after some minutes?
Postfix isn't picking up the changes immediately.

**Comment by g4rf** [comment]
Checked it and yes: It lasts some time till postfix updates it's configuration. So it's no bug anymore but I'll update the docs.
