### ISSUE TITLE
Setting SOCIALACCOUNT_PROVIDERS for Django has no effect

### ISSUE THREAD

**Issue by g4rf** [g4rf/dockerized-mailcow-mailman#2]
I expect that setting `SOCIALACCOUNT_PROVIDERS = {}` will disable the ability to log in with OAuth providers. But I still see them in *Pistorius*.

**Comment by sheveko** [comment]
As mentioned at https://github.com/maxking/docker-mailman/tree/main/web#social-auth create `/opt/mailman-web-data/settings_local.py` for the mailman-web container. Inside write
```python
MAILMAN_WEB_SOCIAL_AUTH = []
```
to disable social authentication.

**Comment by rkl110** [comment]
#3
