### ISSUE TITLE
nothing coming UP after installing

### ISSUE THREAD

**Issue by nv160** [g4rf/dockerized-mailcow-mailman#4]
Getting following errors in mailman-core:

mailman-core  | SMTP_HOST not specified, using the gateway (172.19.199.1) as default
mailman-core  |                                                List of databases
mailman-core  |    Name    |  Owner  | Encoding |  Collate   |   Ctype    | ICU Locale | Locale Provider |  Access privileges
mailman-core  | -----------+---------+----------+------------+------------+------------+-----------------+---------------------
mailman-core  |  mailmandb | mailman | UTF8     | en_US.utf8 | en_US.utf8 |            | libc            |
mailman-core  |  postgres  | mailman | UTF8     | en_US.utf8 | en_US.utf8 |            | libc            |
mailman-core  |  template0 | mailman | UTF8     | en_US.utf8 | en_US.utf8 |            | libc            | =c/mailman         +
mailman-core  |            |         |          |            |            |            |                 | mailman=CTc/mailman
mailman-core  |  template1 | mailman | UTF8     | en_US.utf8 | en_US.utf8 |            | libc            | =c/mailman         +
mailman-core  |            |         |          |            |            |            |                 | mailman=CTc/mailman
mailman-core  | (4 rows)
mailman-core  |
mailman-core  | Postgres is up - continuing
mailman-core  | Using Postfix configuration
mailman-core  | Found configuration file at /opt/mailman/mailman-extra.cfg
mailman-core  | HYPERKITTY_API_KEY found, setting up HyperKitty archiver...
mailman-core  | HYPERKITTY_URL not set, using the default value of http://mailman-web:8000/hyperkitty
mailman-core  | Traceback (most recent call last):
mailman-core  |   File "/usr/bin/mailman", line 8, in <module>
mailman-core  |     sys.exit(main())
mailman-core  |   File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
mailman-core  |     return self.main(*args, **kwargs)
mailman-core  |   File "/usr/lib/python3.10/site-packages/click/core.py", line 1054, in main
mailman-core  |     with self.make_context(prog_name, args, **extra) as ctx:
mailman-core  |   File "/usr/lib/python3.10/site-packages/click/core.py", line 920, in make_context
mailman-core  |     self.parse_args(ctx, args)
mailman-core  |   File "/usr/lib/python3.10/site-packages/click/core.py", line 1613, in parse_args
mailman-core  |     rest = super().parse_args(ctx, args)
mailman-core  |   File "/usr/lib/python3.10/site-packages/click/core.py", line 1378, in parse_args
mailman-core  |     value, args = param.handle_parse_result(ctx, opts, args)
mailman-core  |   File "/usr/lib/python3.10/site-packages/click/core.py", line 2360, in handle_parse_result
mailman-core  |     value = self.process_value(ctx, value)
mailman-core  |   File "/usr/lib/python3.10/site-packages/click/core.py", line 2322, in process_value
mailman-core  |     value = self.callback(ctx, self, value)
mailman-core  |   File "/usr/lib/python3.10/site-packages/mailman/bin/mailman.py", line 95, in initialize_config
mailman-core  |     initialize(value)
mailman-core  |   File "/usr/lib/python3.10/site-packages/mailman/core/initialize.py", line 229, in initialize
mailman-core  |     initialize_2(propagate_logs=propagate_logs)
mailman-core  |   File "/usr/lib/python3.10/site-packages/mailman/core/initialize.py", line 187, in initialize_2
mailman-core  |     config.db = getUtility(IDatabaseFactory, utility_name).create()
mailman-core  |   File "/usr/lib/python3.10/site-packages/mailman/database/factory.py", line 57, in create
mailman-core  |     database.initialize()
mailman-core  |   File "/usr/lib/python3.10/site-packages/mailman/database/base.py", line 117, in initialize
mailman-core  |     self.engine = create_engine(
mailman-core  |   File "<string>", line 2, in create_engine
mailman-core  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
mailman-core  |     return fn(*args, **kwargs)
mailman-core  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 522, in create_engine
mailman-core  |     entrypoint = u._get_entrypoint()
mailman-core  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/url.py", line 662, in _get_entrypoint
mailman-core  |     cls = registry.load(name)
mailman-core  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 343, in load
mailman-core  |     raise exc.NoSuchModuleError(
mailman-core  | sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres

mailman-web error:

mailman-web  | Postgres is up - continuing
mailman-web  | Copying settings_local.py ...
mailman-web  | Compiling locale files in /usr/lib/python3.10/site-packages
mailman-web  | Traceback (most recent call last):
mailman-web  |   File "/opt/mailman-web/manage.py", line 10, in <module>
mailman-web  |     execute_from_command_line(sys.argv)
mailman-web  |   File "/usr/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
mailman-web  |     utility.execute()
mailman-web  |   File "/usr/lib/python3.10/site-packages/django/core/management/__init__.py", line 386, in execute
mailman-web  |     settings.INSTALLED_APPS
mailman-web  |   File "/usr/lib/python3.10/site-packages/django/conf/__init__.py", line 87, in __getattr__
mailman-web  |     self._setup(name)
mailman-web  |   File "/usr/lib/python3.10/site-packages/django/conf/__init__.py", line 74, in _setup
mailman-web  |     self._wrapped = Settings(settings_module)
mailman-web  |   File "/usr/lib/python3.10/site-packages/django/conf/__init__.py", line 183, in __init__
mailman-web  |     mod = importlib.import_module(self.SETTINGS_MODULE)
mailman-web  |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
mailman-web  |     return _bootstrap._gcd_import(name[level:], package, level)
mailman-web  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
mailman-web  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
mailman-web  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
mailman-web  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
mailman-web  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
mailman-web  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
mailman-web  |   File "/opt/mailman-web/settings.py", line 65, in <module>
mailman-web  |     MAILMAN_ARCHIVER_FROM = (os.environ.get('MAILMAN_HOST_IP', gethostbyname(os.environ.get('MAILMAN_HOSTNAME', 'mailman-core'))),)
mailman-web  | socket.gaierror: [Errno -2] Name does not resolve
mailman-web  | python3: can't open file '/usr/lib/python3.10/site-packages/manage.py': [Errno 2] No such file or directory

I can see mailman hostname is exactly pointing to my server when checking with dig. Please guide further if i am missing anything.

**Comment by g4rf** [comment]
I can't see any missing thing on following my guide. Maybe [docker-mailman](https://github.com/maxking/docker-mailman) changed something, so please look at [their wiki](https://github.com/maxking/docker-mailman/wiki) and [issues](https://github.com/maxking/docker-mailman/issues?q=is%3Aissue) and, if nothing helped, open an issue there.

**Comment by nv160** [comment]
Upong googling... I changed my docker-compose.override.yaml postgres database url name

Original: - DATABASE_URL=**postgres**:

Changed to: - DATABASE_URL=**postgresql**:

restarted mailman services and mailman started working

**Comment by helgetelefonmann** [comment]
Should still be updated in README.md, though. It still reads there:
- DATABASE_URL=postgres://mailman:DBPASS@database/mailmandb
